FROM debian:trixie-slim

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    krb5-kdc \
    krb5-admin-server \
    && rm -rf /var/lib/apt/lists/*

COPY kdc.conf /etc/krb5kdc/kdc.conf
COPY krb5.conf /etc/krb5.conf
COPY kadm5.acl /etc/krb5kdc/kadm5.acl
COPY init-kdc.sh /init-kdc.sh

RUN chmod +x /init-kdc.sh

EXPOSE 88/tcp 88/udp 749/tcp

ENTRYPOINT ["/init-kdc.sh"]
