//! Auto-generated from Kafka protocol
//! Message: AlterUserScramCredentialsRequest
//! DO NOT EDIT

use kafka_client_protocol_core::{KafkaMessage, RecordBatch};
use bytes::Bytes;
use uuid::Uuid;

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct ScramCredentialDeletion {
    /// The user name.
    #[kafka(versions = "0+")]
    pub name: String,
    /// The SCRAM mechanism.
    #[kafka(versions = "0+")]
    pub mechanism: i8,
}


#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct ScramCredentialUpsertion {
    /// The user name.
    #[kafka(versions = "0+")]
    pub name: String,
    /// The SCRAM mechanism.
    #[kafka(versions = "0+")]
    pub mechanism: i8,
    /// The number of iterations.
    #[kafka(versions = "0+")]
    pub iterations: i32,
    /// A random salt generated by the client.
    #[kafka(versions = "0+")]
    pub salt: Bytes,
    /// The salted password.
    #[kafka(versions = "0+")]
    pub salted_password: Bytes,
}


#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
#[kafka(api_key = 51, msg_type = "request", valid_versions = "0", flexible_versions = "0+")]
pub struct AlterUserScramCredentialsRequest {
    /// The SCRAM credentials to remove.
    #[kafka(versions = "0+")]
    pub deletions: Vec<ScramCredentialDeletion>,
    /// The SCRAM credentials to update/insert.
    #[kafka(versions = "0+")]
    pub upsertions: Vec<ScramCredentialUpsertion>,
}

