//! Auto-generated from Kafka protocol
//! Message: ConsumerGroupHeartbeatResponse
//! DO NOT EDIT

use kafka_client_protocol_core::{KafkaMessage, RecordBatch};
use bytes::Bytes;
use uuid::Uuid;

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct TopicPartitions {
    /// The topic ID.
    #[kafka(versions = "0+")]
    pub topic_id: Uuid,
    /// The partitions.
    #[kafka(versions = "0+")]
    pub partitions: Vec<i32>,
}


#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct Assignment {
    /// The partitions assigned to the member that can be used immediately.
    #[kafka(versions = "0+")]
    pub topic_partitions: Vec<TopicPartitions>,
}


#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
#[kafka(api_key = 68, msg_type = "response", valid_versions = "0-1", flexible_versions = "0+")]
pub struct ConsumerGroupHeartbeatResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    #[kafka(versions = "0+")]
    pub throttle_time_ms: i32,
    /// The top-level error code, or 0 if there was no error.
    #[kafka(versions = "0+")]
    pub error_code: i16,
    /// The top-level error message, or null if there was no error.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub error_message: Option<String>,
    /// The member id is generated by the consumer starting from version 1, while in version 0, it can be provided by users or generated by the group coordinator.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub member_id: Option<String>,
    /// The member epoch.
    #[kafka(versions = "0+")]
    pub member_epoch: i32,
    /// The heartbeat interval in milliseconds.
    #[kafka(versions = "0+")]
    pub heartbeat_interval_ms: i32,
    /// null if not provided; the assignment otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub assignment: Option<Assignment>,
}

