//! Auto-generated from Kafka protocol
//! Message: ConsumerGroupHeartbeatRequest
//! DO NOT EDIT

use kafka_client_protocol_core::{KafkaMessage, RecordBatch};
use bytes::Bytes;
use uuid::Uuid;

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct TopicPartitions {
    /// The topic ID.
    #[kafka(versions = "0+")]
    pub topic_id: Uuid,
    /// The partitions.
    #[kafka(versions = "0+")]
    pub partitions: Vec<i32>,
}


#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
#[kafka(api_key = 68, msg_type = "request", valid_versions = "0-1", flexible_versions = "0+")]
pub struct ConsumerGroupHeartbeatRequest {
    /// The group identifier.
    #[kafka(versions = "0+")]
    pub group_id: String,
    /// The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process.
    #[kafka(versions = "0+")]
    pub member_id: String,
    /// The current member epoch; 0 to join the group; -1 to leave the group; -2 to indicate that the static member will rejoin.
    #[kafka(versions = "0+")]
    pub member_epoch: i32,
    /// null if not provided or if it didn't change since the last heartbeat; the instance Id otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub instance_id: Option<String>,
    /// null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub rack_id: Option<String>,
    /// -1 if it didn't change since the last heartbeat; the maximum time in milliseconds that the coordinator will wait on the member to revoke its partitions otherwise.
    #[kafka(versions = "0+", default = -1)]
    pub rebalance_timeout_ms: i32,
    /// null if it didn't change since the last heartbeat; the subscribed topic names otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub subscribed_topic_names: Option<Vec<String>>,
    /// null if it didn't change since the last heartbeat; the subscribed topic regex otherwise.
    #[kafka(versions = "1+", nullable_versions = "1+", default = None)]
    pub subscribed_topic_regex: Option<String>,
    /// null if not used or if it didn't change since the last heartbeat; the server side assignor to use otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub server_assignor: Option<String>,
    /// null if it didn't change since the last heartbeat; the partitions owned by the member.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub topic_partitions: Option<Vec<TopicPartitions>>,
}

