//! Auto-generated from Kafka protocol
//! Message: ShareGroupHeartbeatRequest
//! DO NOT EDIT

use kafka_client_protocol_core::{KafkaMessage, RecordBatch};
use bytes::Bytes;
use uuid::Uuid;

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
#[kafka(api_key = 76, msg_type = "request", valid_versions = "1", flexible_versions = "0+")]
pub struct ShareGroupHeartbeatRequest {
    /// The group identifier.
    #[kafka(versions = "0+")]
    pub group_id: String,
    /// The member id generated by the consumer. The member id must be kept during the entire lifetime of the consumer process.
    #[kafka(versions = "0+")]
    pub member_id: String,
    /// The current member epoch; 0 to join the group; -1 to leave the group.
    #[kafka(versions = "0+")]
    pub member_epoch: i32,
    /// null if not provided or if it didn't change since the last heartbeat; the rack ID of consumer otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub rack_id: Option<String>,
    /// null if it didn't change since the last heartbeat; the subscribed topic names otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub subscribed_topic_names: Option<Vec<String>>,
}

