//! Auto-generated from Kafka protocol
//! Message: StreamsGroupHeartbeatRequest
//! DO NOT EDIT

use bytes::Bytes;
use kafka_client_protocol_core::{KafkaMessage, RecordBatch};
use uuid::Uuid;

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct KeyValue {
    /// key of the config
    #[kafka(versions = "0+")]
    pub key: String,
    /// value of the config
    #[kafka(versions = "0+")]
    pub value: String,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct TopicInfo {
    /// The name of the topic.
    #[kafka(versions = "0+")]
    pub name: String,
    /// The number of partitions in the topic. Can be 0 if no specific number of partitions is enforced. Always 0 for changelog topics.
    #[kafka(versions = "0+")]
    pub partitions: i32,
    /// The replication factor of the topic. Can be 0 if the default replication factor should be used.
    #[kafka(versions = "0+")]
    pub replication_factor: i16,
    /// Topic-level configurations as key-value pairs.
    #[kafka(versions = "0+")]
    pub topic_configs: Vec<KeyValue>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct Endpoint {
    /// host of the endpoint
    #[kafka(versions = "0+")]
    pub host: String,
    /// port of the endpoint
    #[kafka(versions = "0+")]
    pub port: u16,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct TaskOffset {
    /// The subtopology identifier.
    #[kafka(versions = "0+")]
    pub subtopology_id: String,
    /// The partition.
    #[kafka(versions = "0+")]
    pub partition: i32,
    /// The offset.
    #[kafka(versions = "0+")]
    pub offset: i64,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct TaskIds {
    /// The subtopology identifier.
    #[kafka(versions = "0+")]
    pub subtopology_id: String,
    /// The partitions of the input topics processed by this member.
    #[kafka(versions = "0+")]
    pub partitions: Vec<i32>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct CopartitionGroup {
    /// The topics the topology reads from. Index into the array on the subtopology level.
    #[kafka(versions = "0+")]
    pub source_topics: Vec<i16>,
    /// Regular expressions identifying topics the subtopology reads from. Index into the array on the subtopology level.
    #[kafka(versions = "0+")]
    pub source_topic_regex: Vec<i16>,
    /// The set of source topics that are internally created repartition topics. Index into the array on the subtopology level.
    #[kafka(versions = "0+")]
    pub repartition_source_topics: Vec<i16>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct Subtopology {
    /// String to uniquely identify the subtopology. Deterministically generated from the topology
    #[kafka(versions = "0+")]
    pub subtopology_id: String,
    /// The topics the topology reads from.
    #[kafka(versions = "0+")]
    pub source_topics: Vec<String>,
    /// The regular expressions identifying topics the subtopology reads from.
    #[kafka(versions = "0+")]
    pub source_topic_regex: Vec<String>,
    /// The set of state changelog topics associated with this subtopology. Created automatically.
    #[kafka(versions = "0+")]
    pub state_changelog_topics: Vec<TopicInfo>,
    /// The repartition topics the subtopology writes to.
    #[kafka(versions = "0+")]
    pub repartition_sink_topics: Vec<String>,
    /// The set of source topics that are internally created repartition topics. Created automatically.
    #[kafka(versions = "0+")]
    pub repartition_source_topics: Vec<TopicInfo>,
    /// A subset of source topics that must be copartitioned.
    #[kafka(versions = "0+")]
    pub copartition_groups: Vec<CopartitionGroup>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct Topology {
    /// The epoch of the topology. Used to check if the topology corresponds to the topology initialized on the brokers.
    #[kafka(versions = "0+")]
    pub epoch: i32,
    /// The sub-topologies of the streams application.
    #[kafka(versions = "0+")]
    pub subtopologies: Vec<Subtopology>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
#[kafka(
    api_key = 88,
    msg_type = "request",
    valid_versions = "0",
    flexible_versions = "0+"
)]
pub struct StreamsGroupHeartbeatRequest {
    /// The group identifier.
    #[kafka(versions = "0+")]
    pub group_id: String,
    /// The member ID generated by the streams consumer. The member ID must be kept during the entire lifetime of the streams consumer process.
    #[kafka(versions = "0+")]
    pub member_id: String,
    /// The current member epoch; 0 to join the group; -1 to leave the group; -2 to indicate that the static member will rejoin.
    #[kafka(versions = "0+")]
    pub member_epoch: i32,
    /// The current endpoint epoch of this client, represents the latest endpoint epoch this client received
    #[kafka(versions = "0+")]
    pub endpoint_information_epoch: i32,
    /// null if not provided or if it didn't change since the last heartbeat; the instance ID for static membership otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub instance_id: Option<String>,
    /// null if not provided or if it didn't change since the last heartbeat; the rack ID of the member otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub rack_id: Option<String>,
    /// -1 if it didn't change since the last heartbeat; the maximum time in milliseconds that the coordinator will wait on the member to revoke its tasks otherwise.
    #[kafka(versions = "0+", default = -1)]
    pub rebalance_timeout_ms: i32,
    /// The topology metadata of the streams application. Used to initialize the topology of the group and to check if the topology corresponds to the topology initialized for the group. Only sent when memberEpoch = 0, must be non-empty. Null otherwise.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub topology: Option<Topology>,
    /// Currently owned active tasks for this client. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub active_tasks: Option<Vec<TaskIds>>,
    /// Currently owned standby tasks for this client. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub standby_tasks: Option<Vec<TaskIds>>,
    /// Currently owned warm-up tasks for this client. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub warmup_tasks: Option<Vec<TaskIds>>,
    /// Identity of the streams instance that may have multiple consumers. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub process_id: Option<String>,
    /// User-defined endpoint for Interactive Queries. Null if unchanged since last heartbeat, or if not defined on the client.
    #[kafka(versions = "0+", default = None)]
    pub user_endpoint: Option<Endpoint>,
    /// Used for rack-aware assignment algorithm. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub client_tags: Option<Vec<KeyValue>>,
    /// Cumulative changelog offsets for tasks. Only updated when a warm-up task has caught up, and according to the task offset interval. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub task_offsets: Option<Vec<TaskOffset>>,
    /// Cumulative changelog end-offsets for tasks. Only updated when a warm-up task has caught up, and according to the task offset interval. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub task_end_offsets: Option<Vec<TaskOffset>>,
    /// Whether all Streams clients in the group should shut down.
    #[kafka(versions = "0+", default = false)]
    pub shutdown_application: bool,
}
