//! Auto-generated from Kafka protocol
//! Message: StreamsGroupHeartbeatResponse
//! DO NOT EDIT

use bytes::Bytes;
use kafka_client_protocol_core::{KafkaMessage, RecordBatch};
use uuid::Uuid;

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct Status {
    /// A code to indicate that a particular status is active for the group membership
    #[kafka(versions = "0+")]
    pub status_code: i8,
    /// A string representation of the status.
    #[kafka(versions = "0+")]
    pub status_detail: String,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct TopicPartition {
    /// topic name
    #[kafka(versions = "0+")]
    pub topic: String,
    /// partitions
    #[kafka(versions = "0+")]
    pub partitions: Vec<i32>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct TaskIds {
    /// The subtopology identifier.
    #[kafka(versions = "0+")]
    pub subtopology_id: String,
    /// The partitions of the input topics processed by this member.
    #[kafka(versions = "0+")]
    pub partitions: Vec<i32>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct Endpoint {
    /// host of the endpoint
    #[kafka(versions = "0+")]
    pub host: String,
    /// port of the endpoint
    #[kafka(versions = "0+")]
    pub port: u16,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
pub struct EndpointToPartitions {
    /// User-defined endpoint to connect to the node
    #[kafka(versions = "0+")]
    pub user_endpoint: Endpoint,
    /// All topic partitions materialized by active tasks on the node
    #[kafka(versions = "0+")]
    pub active_partitions: Vec<TopicPartition>,
    /// All topic partitions materialized by standby tasks on the node
    #[kafka(versions = "0+")]
    pub standby_partitions: Vec<TopicPartition>,
}

#[derive(KafkaMessage, Debug, Clone, Default, PartialEq)]
#[kafka(
    api_key = 88,
    msg_type = "response",
    valid_versions = "0",
    flexible_versions = "0+"
)]
pub struct StreamsGroupHeartbeatResponse {
    /// The duration in milliseconds for which the request was throttled due to a quota violation, or zero if the request did not violate any quota.
    #[kafka(versions = "0+")]
    pub throttle_time_ms: i32,
    /// The top-level error code, or 0 if there was no error
    #[kafka(versions = "0+")]
    pub error_code: i16,
    /// The top-level error message, or null if there was no error.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub error_message: Option<String>,
    /// The member id is always generated by the streams consumer.
    #[kafka(versions = "0+")]
    pub member_id: String,
    /// The member epoch.
    #[kafka(versions = "0+")]
    pub member_epoch: i32,
    /// The heartbeat interval in milliseconds.
    #[kafka(versions = "0+")]
    pub heartbeat_interval_ms: i32,
    /// The maximal lag a warm-up task can have to be considered caught-up.
    #[kafka(versions = "0+")]
    pub acceptable_recovery_lag: i32,
    /// The interval in which the task changelog offsets on a client are updated on the broker. The offsets are sent with the next heartbeat after this time has passed.
    #[kafka(versions = "0+")]
    pub task_offset_interval_ms: i32,
    /// Indicate zero or more status for the group.
    #[kafka(versions = "0+", nullable_versions = "0+")]
    pub status: Option<Vec<Status>>,
    /// Assigned active tasks for this client. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub active_tasks: Option<Vec<TaskIds>>,
    /// Assigned standby tasks for this client. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub standby_tasks: Option<Vec<TaskIds>>,
    /// Assigned warm-up tasks for this client. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub warmup_tasks: Option<Vec<TaskIds>>,
    /// The endpoint epoch set in the response
    #[kafka(versions = "0+")]
    pub endpoint_information_epoch: i32,
    /// Global assignment information used for IQ. Null if unchanged since last heartbeat.
    #[kafka(versions = "0+", nullable_versions = "0+", default = None)]
    pub partitions_by_user_endpoint: Option<Vec<EndpointToPartitions>>,
}
